name: Tests

on:
  push:
    branches: [main]
    paths: ["**/*.py", .github/workflows/test.yml]
  pull_request:
    branches: [main]
    paths: ["**/*.py", .github/workflows/test.yml]
  release:
    types: [published]
  workflow_dispatch:

jobs:
  tests:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}

    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.11

      - name: Run tests
        run: uv run --with '.[test,stats]' pytest --durations 0 --cov .
        env:
          ILOVEPDF_PUBLIC_KEY: ${{ secrets.ILOVEPDF_PUBLIC_KEY }}

  release:
    runs-on: ubuntu-latest
    needs: tests
    if: github.event_name == 'release' && needs.tests.result == 'success'
    steps:
      - name: Check out repo
        uses: actions/checkout@v4

      - name: Set up python
        uses: astral-sh/setup-uv@v6

      - name: Build and publish package to PyPI
        run: |
          uv build
          uv publish --username __token__ --token ${{ secrets.PYPI_TOKEN }}
